Fix linter formatter
ptatarsk/lambda-bird-time-slot-app pull request #1
Opened 2021-04-27 14:55 UTC by ptatarsk

2021-04-29 13:51 UTC, imbaniac requested changes

2021-04-29 13:51 UTC, imbaniac commented on server/.prettierrc
> +{
Seems like all rules are copy of default ones.
Those for sure: printWidth, semi, singleQuote, tabWidth, trailingComma

2021-05-04 10:49 UTC, ptatarsk commented on server/.prettierrc
> +{
Thats true. It's removed from server ans client.

2021-05-04 15:44 UTC, imbaniac approved these changes

2021-05-05 05:52 UTC, merged