Feature/rewrite slot picker
ptatarsk/lambda-bird-time-slot-app pull request #15
Opened 2021-05-06 14:09 UTC by ptatarsk

Done: 

- [x] Rewrite slot picker

- [x] Replace old picker on  rewrited

- [x] Change styles

2021-05-10 11:14 UTC, imbaniac commented
Disable no-prop-types rule and add prop-types to all components
You can do it in a separate task

2021-05-10 13:07 UTC, ptatarsk commented
> Disable no-prop-types rule and add prop-types to all components
> You can do it in a separate task

Done in Feature/add prop types pr. + add auto endOfLine rule.

2021-05-10 13:29 UTC, imbaniac requested changes

2021-05-11 13:45 UTC, ptatarsk commented on client/src/components/shared/SlotPicker/SlotPicker.js
> +    setStartRectCoords({ ...startRectCoords, x: clientX, y: clientY });
It has more properties while ago. Fixed

2021-05-11 13:45 UTC, ptatarsk commented on client/src/components/shared/SlotPicker/SlotPicker.js
> +      setOptions({ ...options, isSelecting: true, isDeselect: true });
Fixed

2021-05-12 05:50 UTC, merged