Feature dockerize app
ptatarsk/lambda-bird-time-slot-app pull request #2
Opened 2021-04-28 12:22 UTC by ptatarsk

2021-04-29 13:54 UTC, imbaniac commented on client/.dockerignore
> +.dockerignore
you've added .dockerignore to .dockerignore)

2021-04-29 14:00 UTC, imbaniac requested changes

2021-04-29 14:00 UTC, imbaniac commented on server/.dockerignore
> +Dockerfile
same as upper comment

2021-04-29 14:00 UTC, imbaniac commented on server/configs/db.config.json
> +  "url": "postgres://mydb:mydb@db:5432/mydb"
You should access those constants from process.env (thanks to docker-compose)

2021-04-29 14:00 UTC, imbaniac commented on server/index.js
> +console.log('url: ', url);
remove console.log

2021-04-29 14:00 UTC, imbaniac commented on server/index.js
> +fastify.listen(3300, '0.0.0.0').catch((err) => {
user port from process.env (from docker-compose)

2021-04-29 14:00 UTC, imbaniac commented on server/index.js
>    console.log('aaaaaa');
remove

2021-05-04 11:02 UTC, ptatarsk commented on client/.dockerignore
> +.dockerignore
Done

2021-05-04 11:02 UTC, ptatarsk commented on server/.dockerignore
> +Dockerfile
Done

2021-05-04 11:03 UTC, ptatarsk commented on server/configs/db.config.json
> +  "url": "postgres://mydb:mydb@db:5432/mydb"
Done in branch Feature/fix server issues

2021-05-04 11:03 UTC, ptatarsk commented on server/index.js
> +console.log('url: ', url);
Done

2021-05-04 11:04 UTC, ptatarsk commented on server/index.js
> +fastify.listen(3300, '0.0.0.0').catch((err) => {
Done

2021-05-04 11:04 UTC, ptatarsk commented on server/index.js
>    console.log('aaaaaa');
Done

2021-05-04 15:45 UTC, imbaniac approved these changes

2021-05-05 05:55 UTC, merged