Feature/incoming request component
ptatarsk/lambda-bird-time-slot-app pull request #22
Opened 2021-05-10 10:58 UTC by ptatarsk

2021-05-10 13:57 UTC, imbaniac approved these changes

2021-05-10 18:14 UTC, imbaniac requested changes

2021-05-11 16:02 UTC, ptatarsk commented on client/src/components/IncomingRequestList/IncomingRequestList.js
> +      selectedRequestData: incomingRequests.find((item) => {
Fixed

2021-05-11 16:26 UTC, imbaniac approved these changes

2021-05-12 10:07 UTC, merged