Feature/add prop types
ptatarsk/lambda-bird-time-slot-app pull request #29
Opened 2021-05-10 13:04 UTC by ptatarsk

2021-05-10 14:22 UTC, imbaniac requested changes

2021-05-10 14:22 UTC, imbaniac commented on client/src/components/shared/Form/Input/Input.js
> +  onChange: null,
settings onChange to default null will crash components in case of mission prop-type

2021-05-11 11:37 UTC, ptatarsk commented on client/src/components/shared/Form/Input/Input.js
> +  onChange: null,
Done

2021-05-11 16:27 UTC, imbaniac approved these changes

2021-05-12 11:53 UTC, merged