Feature/fix jwt username props bug
ptatarsk/lambda-bird-time-slot-app pull request #6
Opened 2021-04-29 11:31 UTC by ptatarsk

Done:

- [x] fix bug with props/local storage
- [x] fix errors setting
- [x] fix functions naming
- [x] add props destructuring
- [x] add optional chaining usage

2021-04-29 15:28 UTC, imbaniac commented
Squash 3 commits with same name

2021-04-29 15:30 UTC, imbaniac requested changes

2021-04-29 15:30 UTC, imbaniac commented on client/src/utils/getFromStorage.js
> +  entities.forEach((entity) => {
try to do with .reduce

2021-05-04 12:17 UTC, ptatarsk commented on client/src/utils/getFromStorage.js
> +  entities.forEach((entity) => {
done

2021-05-04 15:46 UTC, imbaniac approved these changes

2021-05-05 06:58 UTC, merged