Feature/fix server issues
ptatarsk/lambda-bird-time-slot-app pull request #7
Opened 2021-04-29 12:31 UTC by ptatarsk

Done:

- [x] Check client with linter
- [x] Add env variables for server in composer
- [x] Check server with linter
- [x] Rework decorators for db interaction

2021-04-29 15:32 UTC, imbaniac commented
The branch is named fix server issues but contains client changes. Better do in a separate PR

2021-04-29 15:34 UTC, imbaniac requested changes

2021-04-29 15:34 UTC, imbaniac commented on client/src/components/App/App.js
> +    setUserData(getFromStorage('username', 'jwt'));
why go to storage if you have needed data in arguments?

2021-05-04 12:37 UTC, ptatarsk commented on client/src/components/App/App.js
> +    setUserData(getFromStorage('username', 'jwt'));
done

2021-05-04 15:47 UTC, imbaniac approved these changes

2021-05-05 07:33 UTC, merged